pgcommitfest/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'commitfest.views.home'),
    url(r'^activity(?P<rss>\.rss)?/', 'commitfest.views.activity'),
    url(r'^(\d+)/$', 'commitfest.views.commitfest'),
    url(r'^(open|inprogress)/$', 'commitfest.views.redir'),
    url(r'^(?P<cfid>\d+)/activity(?P<rss>\.rss)?/$', 'commitfest.views.activity'),
    url(r'^(\d+)/(\d+)/$', 'commitfest.views.patch'),
    url(r'^(\d+)/(\d+)/edit/$', 'commitfest.views.patchform'),
    url(r'^(\d+)/new/$', 'commitfest.views.newpatch'),
    url(r'^(\d+)/(\d+)/status/(review|author|committer)/$', 'commitfest.views.status'),
    url(r'^(\d+)/(\d+)/close/(reject|feedback|committed|next)/$', 'commitfest.views.close'),
    url(r'^(\d+)/(\d+)/reviewer/(become|remove)/$', 'commitfest.views.reviewer'),
    url(r'^(\d+)/(\d+)/committer/(become|remove)/$', 'commitfest.views.committer'),
    url(r'^(\d+)/(\d+)/(comment|review)/', 'commitfest.views.comment'),
    url(r'^(\d+)/send_email/$', 'commitfest.views.send_email'),
    url(r'^(\d+)/\d+/send_email/$', 'commitfest.views.send_email'),
    url(r'^search/$', 'commitfest.views.global_search'),
    url(r'^ajax/(\w+)/$', 'commitfest.ajax.main'),

    url(r'^selectable/', include('selectable.urls')),

    # Auth system integration
    (r'^(?:account/)?login/?$', 'auth.login'),
    (r'^(?:account/)?logout/?$', 'auth.logout'),
    (r'^auth_receive/$', 'auth.auth_receive'),

    # Account management
    (r'^account/profile/$', 'userprofile.views.userprofile'),
    (r'^account/profile/delmail/$', 'userprofile.views.deletemail'),
    (r'^account/profile/confirm/([0-9a-f]+)/$', 'userprofile.views.confirmemail'),

    # Examples:
    # url(r'^$', 'pgcommitfest.views.home', name='home'),
    # url(r'^pgcommitfest/', include('pgcommitfest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

pgcommitfest/commitfest/models.py
from django.db import models
from django.contrib.admin.models import User

from datetime import datetime

from util import DiffableModel

# We have few enough of these, and it's really the only thing we
# need to extend from the user model, so just create a separate
# class.
class Committer(models.Model):
	user = models.ForeignKey(User, null=False, blank=False, primary_key=True)
	active = models.BooleanField(null=False, blank=False, default=True)

	def __unicode__(self):
		return unicode(self.user)

	@property
	def fullname(self):
		return "%s %s (%s)" % (self.user.first_name, self.user.last_name, self.user.username)

	class Meta:
		ordering = ('user__last_name', 'user__first_name')

class CommitFest(models.Model):
	STATUS_FUTURE=1
	STATUS_OPEN=2
	STATUS_INPROGRESS=3
	STATUS_CLOSED=4
	_STATUS_CHOICES = (
		(STATUS_FUTURE, 'Future'),
		(STATUS_OPEN, 'Open'),
		(STATUS_INPROGRESS, 'In Progress'),
		(STATUS_CLOSED, 'Closed'),
		)
	name = models.CharField(max_length=100, blank=False, null=False, unique=True)
	status = models.IntegerField(null=False, blank=False, default=1, choices=_STATUS_CHOICES)
	startdate = models.DateField(blank=True, null=True)
	enddate = models.DateField(blank=True, null=True)

	@property
	def statusstring(self):
		return [v for k,v in self._STATUS_CHOICES if k==self.status][0]

	@property
	def title(self):
		return "Commitfest %s" % self.name

	@property
	def isopen(self):
		return self.status == self.STATUS_OPEN

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name_plural='Commitfests'
		ordering = ('-startdate',)

class Topic(models.Model):
	topic = models.CharField(max_length=100, blank=False, null=False)

	def __unicode__(self):
		return self.topic


class Patch(models.Model, DiffableModel):
	name = models.CharField(max_length=500, blank=False, null=False, verbose_name='Description')
	topic = models.ForeignKey(Topic, blank=False, null=False)

	# One patch can be in multiple commitfests, if it has history
	commitfests = models.ManyToManyField(CommitFest, through='PatchOnCommitFest')

	# If there is a wiki page discussing this patch
	wikilink = models.URLField(blank=True, null=True, default='')

	# If there is a git repo about this patch
	gitlink = models.URLField(blank=True, null=True, default='')

	# Mailthreads are ManyToMany in the other direction
	#mailthreads_set = ...

	authors = models.ManyToManyField(User, related_name='patch_author', blank=True)
	reviewers = models.ManyToManyField(User, related_name='patch_reviewer', blank=True)

	committer = models.ForeignKey(Committer, blank=True, null=True)

	# Datestamps for tracking activity
	created = models.DateTimeField(blank=False, null=False, auto_now_add=True)
	modified = models.DateTimeField(blank=False, null=False)

	# Materialize the last time an email was sent on any of the threads
	# that's attached to this message.
	lastmail = models.DateTimeField(blank=True, null=True)

	map_manytomany_for_diff = {
		'authors': 'authors_string',
		'reviewers': 'reviewers_string',
		}
	# Some accessors
	@property
	def authors_string(self):
		return ", ".join(["%s %s (%s)" % (a.first_name, a.last_name, a.username) for a in self.authors.all()])

	@property
	def reviewers_string(self):
		return ", ".join(["%s %s (%s)" % (a.first_name, a.last_name, a.username) for a in self.reviewers.all()])

	@property
	def history(self):
		# Need to wrap this in a function to make sure it calls
		# select_related() and doesn't generate a bazillion queries
		return self.patchhistory_set.select_related('by').all()

	def set_modified(self, newmod=None):
		# Set the modified date to newmod, but only if that's newer than
		# what's currently set. If newmod is not specified, use the
		# current timestamp.
		if not newmod:
			newmod = datetime.now()
		if not self.modified or newmod > self.modified:
			self.modified = newmod

	def update_lastmail(self):
		# Update the lastmail field, based on the newest email in any of
		# the threads attached to it.
		threads = list(self.mailthread_set.all())
		if len(threads) == 0:
			self.lastmail = None
		else:
			self.lastmail = max(threads, key=lambda t:t.latestmessage).latestmessage

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'patches'

class PatchOnCommitFest(models.Model):
	# NOTE! This is also matched by the commitfest_patchstatus table,
	# but we hardcoded it in here simply for performance reasons since
	# the data should be entirely static. (Yes, that's something we
	# might re-evaluate in the future)
	STATUS_REVIEW=1
	STATUS_AUTHOR=2
	STATUS_COMMITTER=3
	STATUS_COMMITTED=4
	STATUS_NEXT=5
	STATUS_REJECTED=6
	STATUS_RETURNED=7
	_STATUS_CHOICES=(
		(STATUS_REVIEW, 'Needs review'),
		(STATUS_AUTHOR, 'Waiting on Author'),
		(STATUS_COMMITTER, 'Ready for Committer'),
		(STATUS_COMMITTED, 'Committed'),
		(STATUS_NEXT, 'Moved to next CF'),
		(STATUS_REJECTED, 'Rejected'),
		(STATUS_RETURNED, 'Returned with feedback')
	)
	_STATUS_LABELS=(
		(STATUS_REVIEW, 'default'),
		(STATUS_AUTHOR, 'primary'),
		(STATUS_COMMITTER, 'info'),
		(STATUS_COMMITTED, 'success'),
		(STATUS_NEXT, 'warning'),
		(STATUS_REJECTED, 'danger'),
		(STATUS_RETURNED, 'danger'),
	)
	OPEN_STATUSES=(STATUS_REVIEW, STATUS_AUTHOR, STATUS_COMMITTER)
	OPEN_STATUS_CHOICES=[x for x in _STATUS_CHOICES if x[0] in OPEN_STATUSES]

	patch = models.ForeignKey(Patch, blank=False, null=False)
	commitfest = models.ForeignKey(CommitFest, blank=False, null=False)
	enterdate = models.DateTimeField(blank=False, null=False)
	leavedate = models.DateTimeField(blank=True, null=True)

	status = models.IntegerField(blank=False, null=False, default=STATUS_REVIEW, choices=_STATUS_CHOICES)

	@property
	def is_closed(self):
		return self.status not in self.OPEN_STATUSES

	@property
	def statusstring(self):
		return [v for k,v in self._STATUS_CHOICES if k==self.status][0]

	class Meta:
		unique_together = (('patch', 'commitfest',),)
		ordering = ('-commitfest__startdate', )

class PatchHistory(models.Model):
	patch = models.ForeignKey(Patch, blank=False, null=False)
	date = models.DateTimeField(blank=False, null=False, auto_now_add=True)
	by = models.ForeignKey(User, blank=False, null=False)
	what = models.CharField(max_length=500, null=False, blank=False)

	@property
	def by_string(self):
		return "%s %s (%s)" % (self.by.first_name, self.by.last_name, self.by.username)

	def __unicode__(self):
		return "%s - %s" % (self.patch.name, self.date)

	class Meta:
		ordering = ('-date', )

class MailThread(models.Model):
	# This class tracks mail threads from the main postgresql.org
	# mailinglist archives. For each thread, we store *one* messageid.
	# Using this messageid we can always query the archives for more
	# detailed information, which is done dynamically as the page
	# is loaded.
	# For threads in an active or future commitfest, we also poll
	# the archives to fetch "updated entries" at (ir)regular intervals
	# so we can keep track of when there was last a change on the
	# thread in question.
	messageid = models.CharField(max_length=1000, null=False, blank=False, unique=True)
	patches = models.ManyToManyField(Patch, blank=False, null=False)
	subject = models.CharField(max_length=500, null=False, blank=False)
	firstmessage = models.DateTimeField(null=False, blank=False)
	firstauthor = models.CharField(max_length=500, null=False, blank=False)
	latestmessage = models.DateTimeField(null=False, blank=False)
	latestauthor = models.CharField(max_length=500, null=False, blank=False)
	latestsubject = models.CharField(max_length=500, null=False, blank=False)
	latestmsgid = models.CharField(max_length=1000, null=False, blank=False)

	def __unicode__(self):
		return self.subject

	class Meta:
		ordering = ('firstmessage', )

class MailThreadAttachment(models.Model):
	mailthread = models.ForeignKey(MailThread, null=False, blank=False)
	messageid = models.CharField(max_length=1000, null=False, blank=False)
	attachmentid = models.IntegerField(null=False, blank=False)
	filename = models.CharField(max_length=1000, null=False, blank=True)
	date = models.DateTimeField(null=False, blank=False)
	author = models.CharField(max_length=500, null=False, blank=False)
	ispatch = models.NullBooleanField()

	class Meta:
		ordering = ('-date',)
		unique_together = (('mailthread', 'messageid',), )

class MailThreadAnnotation(models.Model):
	mailthread = models.ForeignKey(MailThread, null=False, blank=False)
	date = models.DateTimeField(null=False, blank=False, auto_now_add=True)
	user = models.ForeignKey(User, null=False, blank=False)
	msgid = models.CharField(max_length=1000, null=False, blank=False)
	annotationtext = models.TextField(null=False, blank=False, max_length=2000)
	mailsubject = models.CharField(max_length=500, null=False, blank=False)
	maildate = models.DateTimeField(null=False, blank=False)
	mailauthor = models.CharField(max_length=500, null=False, blank=False)

	@property
	def user_string(self):
		return "%s %s (%s)" % (self.user.first_name, self.user.last_name, self.user.username)

	class Meta:
		ordering = ('date', )

class PatchStatus(models.Model):
	status = models.IntegerField(null=False, blank=False, primary_key=True)
	statusstring = models.TextField(max_length=50, null=False, blank=False)
	sortkey = models.IntegerField(null=False, blank=False, default=10)

pgcommitfest/commitfest/forms.py
from django import forms
from django.forms import ValidationError
from django.forms.widgets import HiddenInput
from django.db.models import Q
from django.contrib.auth.models import User

from selectable.forms.widgets import AutoCompleteSelectMultipleWidget

from models import Patch, MailThread, PatchOnCommitFest
from lookups import UserLookup
from widgets import ThreadPickWidget
from ajax import _archivesAPI

class CommitFestFilterForm(forms.Form):
	text = forms.CharField(max_length=50, required=False)
	status = forms.ChoiceField(required=False)
	author = forms.ChoiceField(required=False)
	reviewer = forms.ChoiceField(required=False)
	sortkey = forms.IntegerField(required=False)

	def __init__(self, cf, *args, **kwargs):
		super(CommitFestFilterForm, self).__init__(*args, **kwargs)

		self.fields['sortkey'].widget = forms.HiddenInput()

		c = [(-1, '* All')] + list(PatchOnCommitFest._STATUS_CHOICES)
		self.fields['status'] = forms.ChoiceField(choices=c, required=False)

		q = Q(patch_author__commitfests=cf) | Q(patch_reviewer__commitfests=cf)
		userchoices = [(-1, '* All'), (-2, '* None'), (-3, '* Yourself') ] + [(u.id, '%s %s (%s)' % (u.first_name, u.last_name, u.username)) for u in User.objects.filter(q).distinct().order_by('last_name', 'first_name')]
		self.fields['author'] = forms.ChoiceField(choices=userchoices, required=False)
		self.fields['reviewer'] = forms.ChoiceField(choices=userchoices, required=False)

		for f in ('status', 'author', 'reviewer',):
			self.fields[f].widget.attrs = {'class': 'input-medium'}

class PatchForm(forms.ModelForm):
	class Meta:
		model = Patch
		exclude = ('commitfests', 'mailthreads', 'modified', 'lastmail', )
		widgets = {
			'authors': AutoCompleteSelectMultipleWidget(lookup_class=UserLookup, position='top'),
			'reviewers': AutoCompleteSelectMultipleWidget(lookup_class=UserLookup, position='top'),
		}

	def __init__(self, *args, **kwargs):
		super(PatchForm, self).__init__(*args, **kwargs)
		self.fields['authors'].help_text = 'Enter part of name to see list'
		self.fields['reviewers'].help_text = 'Enter part of name to see list'
		self.fields['committer'].label_from_instance = lambda x: '%s %s (%s)' % (x.user.first_name, x.user.last_name, x.user.username)


class NewPatchForm(forms.ModelForm):
	threadmsgid = forms.CharField(max_length=200, required=True, label='Specify thread msgid', widget=ThreadPickWidget)
#	patchfile = forms.FileField(allow_empty_file=False, max_length=50000, label='or upload patch file', required=False, help_text='This may be supported sometime in the future, and would then autogenerate a mail to the hackers list. At such a time, the threadmsgid would no longer be required.')

	class Meta:
		model = Patch
		exclude = ('commitfests', 'mailthreads', 'modified', 'authors', 'reviewers', 'committer', 'wikilink', 'gitlink', 'lastmail', )

def _fetch_thread_choices(patch):
	for mt in patch.mailthread_set.order_by('-latestmessage'):
		ti = sorted(_archivesAPI('/message-id.json/%s' % mt.messageid), key=lambda x: x['date'], reverse=True)
		yield [mt.subject,
			   [('%s,%s' % (mt.messageid, t['msgid']),'From %s at %s' % (t['from'], t['date'])) for t in ti]]


review_state_choices = (
	(0, 'Tested'),
	(1, 'Passed'),
)

def reviewfield(label):
	return forms.MultipleChoiceField(choices=review_state_choices, label=label, widget=forms.CheckboxSelectMultiple, required=False)

class CommentForm(forms.Form):
	responseto = forms.ChoiceField(choices=[], required=True, label='In response to')

	# Specific checkbox fields for reviews
	review_installcheck = reviewfield('make installcheck-world')
	review_implements = reviewfield('Implements feature')
	review_spec = reviewfield('Spec compliant')
	review_doc = reviewfield('Documentation')

	message = forms.CharField(required=True, widget=forms.Textarea)
	newstatus = forms.ChoiceField(choices=PatchOnCommitFest.OPEN_STATUS_CHOICES, label='New status')

	def __init__(self, patch, poc, is_review, *args, **kwargs):
		super(CommentForm, self).__init__(*args, **kwargs)
		self.is_review = is_review

		self.fields['responseto'].choices = _fetch_thread_choices(patch)
		self.fields['newstatus'].initial = poc.status
		if not is_review:
			del self.fields['review_installcheck']
			del self.fields['review_implements']
			del self.fields['review_spec']
			del self.fields['review_doc']

	def clean_responseto(self):
		try:
			(threadid, respid) = self.cleaned_data['responseto'].split(',')
			self.thread = MailThread.objects.get(messageid=threadid)
			self.respid = respid
		except MailThread.DoesNotExist:
			raise ValidationError('Selected thread appears to no longer exist')
		except:
			raise ValidationError('Invalid message selected')
		return self.cleaned_data['responseto']

	def clean(self):
		if self.is_review:
			for fn,f in self.fields.items():
				if fn.startswith('review_') and self.cleaned_data.has_key(fn):
					if '1' in self.cleaned_data[fn] and not '0' in self.cleaned_data[fn]:
						self.errors[fn] = (('Cannot pass a test without performing it!'),)
		return self.cleaned_data

class BulkEmailForm(forms.Form):
	reviewers = forms.CharField(required=False, widget=HiddenInput())
	authors = forms.CharField(required=False, widget=HiddenInput())
	subject = forms.CharField(required=True)
	body = forms.CharField(required=True, widget=forms.Textarea)
	confirm = forms.BooleanField(required=True, label='Check to confirm sending')

	def __init__(self, *args, **kwargs):
		super(BulkEmailForm, self).__init__(*args, **kwargs)

pgcommitfest/commitfest/templates/patch.html
{%extends "base.html"%}
{%load commitfest%}
{%block contents%}
{%include "patch_commands.inc"%}
<table class="table table-bordered">
  <tbody>
    <tr>
      <th>Title</th>
      <td>{{patch.name}}</td>
    </tr>
    <tr>
      <th>Topic</th>
      <td>{{patch.topic}}</td>
    </tr>
    <tr>
      <th>Created</th>
      <td>{{patch.created}}</td>
    </tr>
    <tr>
      <th style="white-space: nowrap;">Last modified</th>
      <td>{{patch.modified}} ({{patch.modified|timesince}} ago)</td>
    </tr>
    <tr>
      <th style="white-space: nowrap;">Latest email</th>
      <td>{%if patch.lastmail%}{{patch.lastmail}} ({{patch.lastmail|timesince}} ago){%endif%}</td>
    </tr>
    <tr>
      <th>Status</th>
      <td>{%for c in patch_commitfests %}
	<div style="margin-bottom: 3px;">{{c.commitfest}}: <span class="label label-default">{{c.statusstring}}</span></div>
	{%endfor%}
      </td>
    </tr>
    <tr>
      <th>Authors</th>
      <td>{{patch.authors_string}}</td>
    </tr>
    <tr>
      <th>Reviewers</th>
      <td>{{patch.reviewers_string}}<a href="reviewer/{{is_reviewer|yesno:"remove,become"}}/" class="btn btn-default pull-right">{{is_reviewer|yesno:"Remove from reviewers,Become reviewer"}}</a></td>
    </tr>
    <tr>
      <th>Committer</th>
      <td>{%if patch.committer%}{{patch.committer.fullname}}{%endif%}
{%if is_committer%}<a href="committer/{{is_this_committer|yesno:"remove,become"}}/" class="btn btn-default pull-right">{{is_this_committer|yesno:"Unclaim as committer,Claim as committer"}}</a>{%endif%}
      </td>
    </tr>
    <tr>
      <th>Links</th>
      <td>
	{%if patch.wikilink%}<a href="{{patch.wikilink}}">Wiki</a>{%endif%}
	{%if patch.gitlink%}<a href="{{patch.gitlink}}">Git</a>{%endif%}
      </td>
    </tr>
    <tr>
      <th>Emails</th>
      <td>
{%if user.is_authenticated%}
	<div style="float:right"><button class="btn btn-default" onclick="attachThread({{cf.id}},{{patch.id}})">Attach thread</button></div>
{%else%}
	<div style="float:right"><button class="btn btn-default" onclick="location.href='/account/login/?next=/{{cf.id}}/{{patch.id}}/%3Fattachthreadnow'">Attach thread</button></div>
{%endif%}
	<dl>
	{%for t in patch.mailthread_set.all%}
	 <dt><a href="http://www.postgresql.org/message-id/flat/{{t.messageid}}/">{{t.subject}}</a> <button type="button" class="close close-nofloat" title="Detach this thread" onclick="detachThread({{cf.id}},{{patch.id}},'{{t.messageid}}')">&times;</button></dt>
	 <dd>
	  First at <a href="http://www.postgresql.org/message-id/{{t.messageid}}/">{{t.firstmessage}}</a> by {{t.firstauthor|hidemail}}<br/>
	  Latest at <a href="http://www.postgresql.org/message-id/{{t.latestmsgid}}/">{{t.latestmessage}}</a> by {{t.latestauthor|hidemail}}<br/>
	  {%for ta in t.mailthreadattachment_set.all%}
	  {%if forloop.first%}
	  Latest attachment (<a href="http://www.postgresql.org/message-id/attachment/{{ta.attachmentid}}/{{ta.filename}}">{{ta.filename}}</a>) at <a href="http://www.postgresql.org/message-id/{{ta.messageid}}/">{{ta.date}}</a> from {{ta.author|hidemail}} <button type="button" class="btn btn-default btn-xs" data-toggle="collapse" data-target="#att{{t.pk}}" title="Show all attachments"><i class="glyphicon glyphicon-plus"></i></button>
           <div id="att{{t.pk}}" class="collapse">
          {%endif%}
           &nbsp;&nbsp;&nbsp;&nbsp;Attachment (<a href="http://www.postgresql.org/message-id/attachment/{{ta.attachmentid}}/{{ta.filename}}">{{ta.filename}}</a>) at <a href="http://www.postgresql.org/message-id/{{ta.messageid}}/">{{ta.date}}</a> from {{ta.author|hidemail}} (Patch: {{ta.ispatch|yesno:"Yes,No,Pending check"}})<br/>
          {%if forloop.last%}</div>{%endif%}
	  {%endfor%}
	   <div>
	     {%for a in t.mailthreadannotation_set.all%}
	     {%if forloop.first%}
	     <h4>Annotations</h4>
	     <table class="table table-bordered table-striped table-condensed small">
	       <thead>
		 <tr>
		   <th>When</th>
		   <th>Who</th>
		   <th>Mail</th>
		   <th>Annotation</th>
		 </tr>
	       </thead>
	       <tbody>
	     {%endif%}
	         <tr>
		   <td>{{a.date}}</td>
		   <td style="white-space: nowrap">{{a.user_string}}</td>
		   <td style="white-space: nowrap">From {{a.mailauthor}}<br/>at <a href="http://www.postgresql.org/message-id/{{a.msgid}}/">{{a.maildate}}</a></td>
		   <td width="99%">{{a.annotationtext}} <button type="button" class="close" title="Delete this annotation" onclick="deleteAnnotation({{a.id}})">&times;</button></td>
		 </tr>
	     {%if forloop.last%}
               </body>
             </table>
             {%endif%}
	     {%endfor%}
	     <button class="btn btn-xs btn-default" onclick="addAnnotation({{t.id}})">Add annotation</button>
	   </div>
	 </dd>
	{%endfor%}
	</dl>
      </td>
    </tr>
    <tr>
      <th>History</th>
      <td>
	<div style="max-height: 200px; overflow-y: scroll;">
	<table class="table table-bordered table-striped table-condensed">
	  <thead>
	    <tr>
	      <th>When</th>
	      <th>Who</th>
	      <th>What</th>
	    </tr>
	  </thead>
	  <tbody>
	    {%for h in patch.history %}	  
	    <tr>
	      <td style="white-space: nowrap;">{{h.date}}</td>
	      <td style="white-space: nowrap;">{{h.by_string}}</td>
	      <td width="99%">{{h.what}}</td>
	    </tr>
	    {%endfor%}
	  </tbody>
	</table>
	</div>
      </td>
    </tr>
  </tbody>
</table>

{%include "patch_commands.inc"%}

{%comment%}commit dialog{%endcomment%}
<div class="modal fade" id="commitModal" role="dialog">
 <div class="modal-dialog modal-lg">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
       <h3>Flag as committed</h3>
     </div>
     <div class="modal-body">
       <form class="form" style="margin-bottom: 5px;">
	 <div class="form-group">
	   <label for="committerlist">Committer</label>
	   <select id="committerSelect" class="form-control">
	     <option value="" style="display:none;"></option>
	     {%for c in committers%}
	     <option value="{{c.user.username}}">{{c.user.first_name}} {{c.user.last_name}}</option>
	     {%endfor%}
	   </select>
	 </div>
     </div>
     <div class="modal-footer">
       <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
       <a href="#" class="btn btn-default btn-primary" id="doCommitButton">Flag as committed</a>
     </div>
   </div>
 </div>
</div>

{%include "thread_attach.inc"%}
{%comment%}Modal dialog for adding annotation{%endcomment%}
<div class="modal fade" id="annotateModal" role="dialog">
 <div class="modal-dialog modal-lg"><div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
   <h3>Add annotation</h3>
  </div>
  <div id="annotateMessageBody" class="modal-body">
   <div>Pick one of the messages in this thread</div>
   <div id="annotateListWrap">
    <select id="annotateMessageList" style="width:100%;" onChange="annotateMsgPicked()">
    </select>
   </div>
   <div>Or copy/paste the message-id:</div>
   <div id="annotateMsgidWrap">
     <input id="annotateMsgId" type="text" style="width:100%" onKeyUp="annotateChanged()">
   </div>
   <div><br/></div>
   <div>Enter a messages for the annotation</div>
   <div id="annotateTextWrap">
     <input id="annotateMessage" type="text" style="width:100%" onKeyUp="annotateChanged()">
   </div>
  </div>
  <div class="modal-footer">
   <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
   <a href="#" id="doAnnotateMessageButton" class="btn btn-default btn-primary disabled">Add annotation</a>
  </div>
 </div></div>
</div>
{%endblock%}

{%block morescript%}
<script language="javascript">
$(document).ready(function() {
   $('button.close-nofloat').each(function(i,o) {
      $(o).tooltip();
   });
});
{%if attachnow%}
$(document).ready(function() {
   attachThread({{cf.id}},{{patch.id}}, function() {
      document.location.replace('/{{cf.id}}/{{patch.id}}/');
   });
});
{%endif%}
</script>
{%endblock%}